backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: "site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
# publish_mode: editorial_workflow
site_url: https://infallible-franklin-e50f20.netlify.com
collections:
  - name: "news"
    label: "News"
    create: true
    show_preview_links: true
    preview_path: "news/{{slug}}"
    slug: "{{slug}}"
    folder: "site/content/news"
    media_folder: ''
    editor:
      preview: false
    preview_path_date_field: "updated_on"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Summary", name: "summary", widget: "string"}
      - label: "Categories"
        name: "news/categories"
        widget: "select"
        multiple: true
        options:
          - { label: "Games", value: "games" }
          - { label: "Press Release", value: "press" }
          - { label: "Careers", value: "careers" }
      - {label: "Featured Post", name: "featured_post", widget: "boolean"}
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt text, widget: string}
          - {name: title, label: Title, widget: string}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "work"
    label: "Work"
    label_singular: "work"
    how_preview_links: true
    preview_path: "work/{{slug}}"
    editor:
      preview: false
    folder: "site/content/work/pages"
    create: true
    preview_path_date_field: "updated_on"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number"}
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - {label: "Video active", name: "active", widget: "boolean", default: false}
          - {name: src, label: Image, widget: image}
          - {name: id, label: Video, widget: string, required: false}
          - {name: alt, label: Alt text, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Media", name: "media", widget: "object", fields: [
          {label: "Screenshots", name: "screenshots",  widget: "list", fields: [
              {name: src, label: Image, widget: image},
              {name: alt, label: Alt text, widget: string}
          ]},
          {label: "Concept Art", name: "concepts",  widget: "list", fields: [
            {name: src, label: Image, widget: image},
            {name: alt, label: Alt text, widget: string}
          ]},
          {label: "Videos", name: "videos",  widget: "list", fields: [
            {name: id, label: Video, widget: string},
            {name: name, label: name, widget: string}
          ]},
      ]}
      -  {label: "Testimonials", name: "Testimonials",  widget: "list", fields: [
            {name: name, label: Name, widget: string},
            {name: position, label: Position, widget: string},
            {name: company, label: Company, widget: string},
            {name: src, label: Image, widget: image},
            {name: alt, label: Alt text, widget: string},
            {name: body, label: Body, widget: markdown}
      ]}
  - name: "games"
    label: "Games"
    label_singular: "Game"
    editor:
      preview: false
    folder: "site/content/games/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Genre", name: "genre", widget: "string"}
      - {label: "Players", name: "players", widget: "string", required: false}
      - label: "Platforms"
        name: "platforms"
        widget: "relation"
        multiple: true
        collection: "platforms"
        searchFields: ["name"]
        valueField: "value"
        displayFields: ["name"]
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - {label: "Video active", name: "active", widget: "boolean", default: false}
          - {name: src, label: Image, widget: image}
          - {name: id, label: Video, widget: string, required: false}
          - {name: alt, label: Alt text, widget: string}
      - {label: "Featured Trailer", name: "video", widget: string}
      - {label: "Overview", name: "overview", widget: object, fields: [
          {label: "body", name: "body", widget: "markdown",  required: true}
        ]}
      - {label: "Media", name: "media", widget: "object", fields: [
          {label: "Screenshots", name: "screenshots",  widget: "list", fields: [
          {name: src, label: Image, widget: image},
          {name: alt, label: Alt text, widget: string}
          ]},
          {label: "Concept Art", name: "concepts",  widget: "list", fields: [
          {name: src, label: Image, widget: image},
          {name: alt, label: Alt text, widget: string}
          ]},
          {label: "Videos", name: "videos",  widget: "list", fields: [
          {name: id, label: Video, widget: image},
          {name: name, label: name, widget: string}
          ]},
        ]}
      - {label: "Buy", name: "buy", widget: list,  required: false, fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Platforms", name: "platforms", widget: "relation", multiple: true, collection: "platforms", searchFields: ["name"], valueField: "value", displayFields: ["name"]}
          {name: url , label: Url, widget: string}
        ]}
  - name: "platforms"
    label: "Platforms"
    folder: "site/data/platforms"
    extension: "yaml"
    identifier_field: name
    create: true
    editor:
      preview: false
    fields:
      - {label: "Platform", name: "name", widget: string}
      - {label: "Value", name: "value", widget: string}
      - {label: "Icon", name: "icon", widget: image}
  - name: "careers"
    label: "Careers"
    label_singular: "Careers"
    editor:
      preview: false
    folder: "site/content/careers/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Categories"
        name: "careers/categories"
        widget: "select"
        options:
          - { label: "Art", value: "art" }
          - { label: "Engineering", value: "engineering" }
          - { label: "Design", value: "design" }
          - { label: "Production", value: "production" }
          - { label: "QA", value: "qa" }
          - { label: "Marketing", value: "marketing" }
          - { label: "Studio", value: "studio" }
      - label: "Position type"
        name: "position_type"
        widget: "select"
        options:
          - { label: "Part time", value: "part" }
          - { label: "Full Time", value: "full" }
      - {label: "email", name: "email", widget: "string"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Hero Header", name: header, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Logo", name: "logo", widget: "image"},
              {label: "title", name: "title", widget: "string"},
              {label: "Link", name: "link", widget: "string"},
              {label: "Video", name: "video", widget: string},
              {label: "Video Banner Active", name: "video_active", widget: "boolean"}
            ]}
      - file: "site/content/work/_index.md"
        label: "Our Work Page"
        name: "work"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label: "Featured Image"
            name: "featured_image"
            widget: "object"
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt text, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/games/_index.md"
        label: "Games"
        name: "games"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label: "Featured Image"
            name: "featured_image"
            widget: "object"
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt text, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/careers/_index.md"
        label: "Working for us Page"
        name: "careers"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label: "Featured Image"
            name: "featured_image"
            widget: "object"
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt text, widget: string}
          - {label: Body, name: body, widget: markdown}
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Body", name: "body", widget: string}
              - {label: "About",  name: "about", widget: list, fields: [
                  {label: "Title", name: "title", widget: string},
                  {name: image, label: Image, widget: object, fields: [
                    {name: src, label: Image, widget: image},
                    {name: alt, label: Alt text, widget: string}
                  ]},
                  {label: Body, name: body, widget: markdown}
                ]
              }
          - label: "Values"
            name: "values"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Body", name: "body", widget: string}
              - {label: "Values",  name: "values", widget: list, fields: [
                  {label: "Title", name: "title", widget: string},
                  {label: "Body", name: "body", widget: string}
                ]}
          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Body", name: "body", widget: string}
              - {name: image, label: Image, widget: object, fields: [
                  {name: src, label: Image, widget: image},
                  {name: alt, label: Alt text, widget: string}
                ]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/privacy/_index.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/terms_conditions/_index.md"
        label: "Terms & Conditions Page"
        name: "terms"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "site/data/navigation.yaml"
        fields:
          - label: "Small Menu on/off"
            name: "active"
            widget: "boolean"
            default: false
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
      - label: "GDPR"
        name: "gdpr"
        file: "site/data/gdpr.yaml"
        fields:
          - label: "Use Osana Cookie Content"
            name: "osana"
            widget: object
            fields:
              - {label: "Osana on/off", name: "active", widget: "boolean", default: false}
              - {label: Script , name: script, widget: string}
          - label: "Simple Cookie Consent"
            name: "consent"
            widget: object
            fields:
              - {label: Message, name: message, widget: string, default: "This website uses cookies to ensure you get the best experience on our website."}
              - {label: Dismiss, name: dismiss, widget: string, default: "Got it!"}
              - {label: Link, name: link, widget: string, default: "Privacy Policy"}
              - {label: Url, name: url, widget: string}
      - label: "Contact"
        name: "contact"
        file: "site/data/contact.yaml"
        fields:
          - label: "Contacts"
            name: "contacts"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string }
              - {label: Type, name: type, widget: select, options: ["Telephone", "Email"]}
              - {label: Content, name: content, widget: string }
          - label: "Address"
            name: "address"
            widget: "markdown"
          - label: "Legal"
            name: "legal"
            widget: "markdown"
          - label: "Registration"
            name: "registration"
            widget: "markdown"
      - label: "Social Media"
        name: "socialmedia"
        file: "site/data/socialmedia.yaml"
        fields:
          - label: "Twitter Feed"
            name: "twitter"
            widget: object
            fields:
              - label: "On/Off"
                name: "active"
                widget: "boolean"
                default: false
              - label: "Feed Url"
                name: "url"
                widget: "string"
          - label: "Social Links"
            name: "links"
            widget: "list"
            fields:
              - label: "Type"
                name: "type"
                widget: string
              - label: "id"
                name: "id"
                widget: string
              - label: "url"
                name: "url"
                widget: string
