baseurl = "/"
languageCode = "en"
languageLang = "en"
defaultContentLanguage = "en"
title = "Firespite Studio"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = ""


############################
## Advanced options below ##
############################

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[imaging]
  resampleFilter = "lanczos"
  quality = 60
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["section", "games", "careers", "contact", "admin"]

# Taxonomies.
#pluralizeListTitles=false
#preserveTaxonomyNames=true
[taxonomies]
  tag = "news/tags"
  category = "news/categories"
  career = "careers/categories"
  platform = "platforms"
  game = "games"
  #archm = "/news/archm"
  #archy = "/news/archy"
  #publication_type = "publication_types"
  #author = "authors"

[permalinks]
  work = "/work/:slug"
  knowledge = "/support/knowledgebase/:slug"
  news = "/news/:year/:month/:slug/"
  archm = "/news/:year/:month/"
  archy = "/news/:year/"




