############################
## Menu
############################

[[navbar]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 1
[[navbar]]
    identifier = "case_studies"
    name = "Case Studies"
    url = "/case-studies"
    weight = 2
[[navbar]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3
[[navbar]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4
[[secondary]]
    identifier = "terms"
    name = "Terms & Conditions"
    url = "/terms_conditions"
    weight = 1
[[secondary]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy"
    weight = 2


