############################
## Basic Info
############################

custom_navbar= false
cms_navbar = true
preloader = true
host_name = "https://firesprite.com/"
description = "Firesprite - A next generation game development studio based in the heart of Liverpool, UK."
logo_large="/images/logo-full.png"
logo_small="/images/logo-icon.png"
logo_mobile="/images/logo-full.png"

############################
## Site Features
############################

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2 January 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 0

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

############################
## News
############################
[news]
  archive_menu_detail = false

############################
## Maps
############################
[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  engine = 0
  api_key = ""
  zoom = 15

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-159821960-1"
  google_tag_manager = ""

############################
## Privacy
############################

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
